- name: Create EC2 instance
  hosts: all
  gather_facts: no
  vars:
    instance_type: t2.micro
    ami: ami-0da13880f921c96a5
    region: ap-northeast-3
    key_name: my-key-pair
    security_group: default
    tag_name: my-instance
  tasks:
    - name: Launch EC2 Instance
      amazon.aws.ec2_instance:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        region: "{{ region }}"
        group: "{{ security_group }}"
        instance_tags:
          Name: "{{ tag_name }}"
        wait: true
      register: ec2

- name: Print Public IP Address
          
